analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.975962799275294
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0
  brandStrength: 0.625
  rhythmicContrast: 1
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 1
purpose: []
favicon: null
name: Scott DeNoon
typography_spectrum: 0.7364181496668607
